# 새의 군집 정도 확인

In [1]:
# 데이터 가져오기
import pandas as pd
s_df = pd.read_csv('../../datasets/p_logistic swarm_behaviour/Swarm_Behaviour.csv')
s_df

,x1,y1,xVel1,yVel1,xA1,yA1,xS1,yS1,xC1,yC1,...,yVel200,xA200,yA200,xS200,yS200,xC200,yC200,nAC200,nS200,Swarm_Behaviour
0,562.05,-0.62,-10.70,-4.33,0.00,0.00,0.0,0.0,0.00,0.00,...,-15.15,0.00,0.00,0.00,0.00,0.00,0.00,28,0,0.0
1,175.66,-57.09,2.31,-2.67,0.00,0.00,0.0,0.0,0.00,0.00,...,-3.48,0.00,0.00,0.00,0.00,0.00,0.00,4,0,0.0
2,200.16,-320.07,4.01,-6.37,0.00,0.00,0.0,0.0,0.18,-0.26,...,-9.38,0.00,0.00,0.00,0.00,-0.11,-0.30,15,1,0.0
3,316.99,-906.84,0.85,9.17,-0.17,1.03,0.0,0.0,0.00,0.00,...,10.39,-0.26,1.01,0.00,0.00,0.00,0.00,16,0,0.0
4,1277.68,908.54,-2.02,8.23,-1.00,1.00,0.0,0.0,0.00,0.00,...,13.91,-1.00,0.00,3.21,15.67,0.00,0.00,12,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23304,-225.85,128.99,12.19,-7.56,-1.00,0.00,0.0,0.0,0.00,0.00,...,-5.06,-1.00,-1.00,-3.99,0.21,0.00,0.00,17,1,0.0
23305,-1352.02,-233.03,-0.86,-4.37,-0.07,-0.55,0.0,0.0,0.28,0.02,...,-12.41,-0.15,-0.70,0.00,0.00,0.02,0.07,69,1,0.0
23306,-1360.61,-778.11,-2.89,-1.17,0.00,0.00,0.0,0.0,0.00,0.00,...,-14.78,0.00,0.00,0.00,0.00,0.00,0.00,20,1,0.0
23307,987.11,615.69,-5.61,-2.92,-1.00,-1.00,0.0,0.0,0.00,0.00,...,9.78,-1.00,-1.00,0.00,0.00,0.00,0.00,29,0,0.0
23308,938.12,-924.87,11.18,2.85,0.10,-0.02,0.0,0.0,0.06,0.31,...,-2.90,-0.13,-0.29,1.31,0.38,0.00,0.00,2,1,0.0

In [2]:
pre_s_df = s_df.copy()

In [3]:
# 결측치
pre_s_df.isna().sum().sum()

0

In [4]:
# 중복값 확인
pre_s_df.duplicated().sum()

4607

In [5]:
# 중복값 삭제
pre_s_df = pre_s_df.drop_duplicates()
pre_s_df = pre_s_df.reset_index(drop=True)
pre_s_df.duplicated().sum()

0

In [6]:
pre_s_df

,x1,y1,xVel1,yVel1,xA1,yA1,xS1,yS1,xC1,yC1,...,yVel200,xA200,yA200,xS200,yS200,xC200,yC200,nAC200,nS200,Swarm_Behaviour
0,562.05,-0.62,-10.70,-4.33,0.00,0.00,0.0,0.0,0.00,0.00,...,-15.15,0.00,0.00,0.00,0.00,0.00,0.00,28,0,0.0
1,175.66,-57.09,2.31,-2.67,0.00,0.00,0.0,0.0,0.00,0.00,...,-3.48,0.00,0.00,0.00,0.00,0.00,0.00,4,0,0.0
2,200.16,-320.07,4.01,-6.37,0.00,0.00,0.0,0.0,0.18,-0.26,...,-9.38,0.00,0.00,0.00,0.00,-0.11,-0.30,15,1,0.0
3,316.99,-906.84,0.85,9.17,-0.17,1.03,0.0,0.0,0.00,0.00,...,10.39,-0.26,1.01,0.00,0.00,0.00,0.00,16,0,0.0
4,1277.68,908.54,-2.02,8.23,-1.00,1.00,0.0,0.0,0.00,0.00,...,13.91,-1.00,0.00,3.21,15.67,0.00,0.00,12,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18697,-425.25,104.59,-9.43,-2.66,-0.95,-0.33,0.0,0.0,-0.97,-0.25,...,2.00,-0.97,0.23,0.00,0.00,-0.96,0.27,3,0,1.0
18698,-1040.34,491.19,4.45,-5.67,0.00,0.00,0.0,0.0,0.14,-0.29,...,-4.73,0.00,0.00,0.00,0.00,-0.31,-0.07,11,0,0.0
18699,1079.89,208.79,-11.67,-4.72,0.00,0.00,0.0,0.0,0.00,0.00,...,-3.93,0.00,0.00,0.00,0.00,0.00,0.00,51,0,0.0
18700,-40.92,382.70,2.21,4.53,0.00,1.00,0.0,0.0,0.00,0.00,...,13.83,0.00,1.00,0.00,0.00,0.00,0.00,1,0,0.0
18701,-1352.02,-233.03,-0.86,-4.37,-0.07,-0.55,0.0,0.0,0.28,0.02,...,-12.41,-0.15,-0.70,0.00,0.00,0.02,0.07,69,1,0.0

In [7]:
# # 이상치 삭제 진행을 위한 정규화 작업
# from sklearn.preprocessing import StandardScaler

# std = StandardScaler()
# result = std.fit_transform(pre_s_df)
# std_pre_s_df = pd.DataFrame(result, columns=pre_s_df.columns)
# std_pre_s_df

In [8]:
# # 이상치 제거
# condition = True
# error_count = []

# for column in std_pre_s_df.columns:
#     if std_pre_s_df[column].between(-1.96, 1.96) is True:
#         error_count.append(std_pre_s_df[column].between(-1.96, 1.96).count())
#     condition &= std_pre_s_df[column].between(-1.96, 1.96)

# std_pre_s_df = std_pre_s_df[condition]
# std_pre_s_df

In [9]:
# # 이상치 제거한 데이터를 인덱스 번호에 맞게 가져오기
# pre_s_df = pre_s_df.iloc[std_pre_s_df.index].reset_index(drop=True)
# pre_s_df

In [10]:
pre_s_df['Swarm_Behaviour'].unique()

array([0., 1.])

In [11]:
pre_s_df['Swarm_Behaviour'].value_counts()

Swarm_Behaviour
0.0    12158
1.0     6544
Name: count, dtype: int64

# Cycle01
- Logistic 분류 훈련

In [11]:
# # smote를 이용하여 target 데이터 분포를 맞춘다. 
# from imblearn.over_sampling import SMOTE
# from sklearn.model_selection import train_test_split

# features, targets = pre_s_df.iloc[:, :-1], pre_s_df.iloc[:, -1]

# X_train, X_test, y_train, y_test = \
# train_test_split(features, targets, stratify=targets, test_size=0.2, random_state=124)

# smote = SMOTE(random_state=124)
# over_X_train, over_y_train = smote.fit_resample(X_train, y_train)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

features, targets = pre_s_df.iloc[:, :-1], pre_s_df.iloc[:, -1]

X_train, X_test, y_train, y_test = \
train_test_split(features, targets, test_size=0.2, stratify=targets, random_state=321)

lg = LogisticRegression(solver='liblinear', random_state=321, max_iter=10000)
# lg.fit(over_X_train, over_y_train)
lg.fit(X_train, y_train)
prediction = lg.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score, precision_score , recall_score , confusion_matrix, ConfusionMatrixDisplay, f1_score, roc_auc_score
import matplotlib.pyplot as plt

def get_evaluation(y_test, prediction, classifier=None, X_test=None):
    confusion = confusion_matrix(y_test, prediction)
    accuracy = accuracy_score(y_test , prediction)
    precision = precision_score(y_test , prediction)
    recall = recall_score(y_test , prediction)
    f1 = f1_score(y_test, prediction)
    roc_auc = roc_auc_score(y_test, prediction)

    print('오차 행렬')
    print(confusion)
    print('정확도: {0:.4f}, 정밀도: {1:.4f}, 재현율: {2:.4f}, F1:{3:.4f}, AUC:{4:.4f}'.format(accuracy , precision ,recall, f1, roc_auc))
    print("#" * 75)
    
    if classifier is not None and  X_test is not None:
        fig, axes = plt.subplots(nrows=1, ncols=2, figsize=(10,4))
        titles_options = [("Confusion matrix", None), ("Normalized confusion matrix", "true")]

        for (title, normalize), ax in zip(titles_options, axes.flatten()):
            disp = ConfusionMatrixDisplay.from_estimator(classifier, X_test, y_test, ax=ax, cmap=plt.cm.Blues, normalize=normalize)
            disp.ax_.set_title(title)
        plt.show()

In [ ]:
get_evaluation(y_test, prediction, lg, X_test)

# Cycle02 
- 다수의 feature가 있어서 차원 축소 진행

In [ ]:
from sklearn.decomposition import PCA

pca = PCA(n_components=15)

pca_train = pca.fit_transform(X_train)

pca_columns = [f'pca{i + 1}' for i in range(pca_train.shape[1])]
pca_train_df = pd.DataFrame(pca_train, columns=pca_columns)
pca_train_df.loc[:, 'target'] = y_train

In [ ]:
# 보존률
print(pca.explained_variance_ratio_)
print(pca.explained_variance_ratio_.sum())

In [ ]:
# pca 후 target 데이터 결측치 삭제
pca_train_df.isna().sum()

In [ ]:
pca_train_df = pca_train_df.dropna().reset_index(drop=True)

In [ ]:
pca_train_df.isna().sum()

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

features, targets = pca_train_df.iloc[:, :-1], pca_train_df.iloc[:, -1]

X_train, X_test, y_train, y_test = \
train_test_split(features, targets, test_size=0.2, stratify=targets, random_state=321)

lg = LogisticRegression(solver='liblinear', penalty='l2', random_state=321, max_iter=10000)
lg.fit(X_train, y_train)
prediction = lg.predict(X_test)

In [ ]:
get_evaluation(y_test, prediction, lg, X_test)

In [ ]:
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
from sklearn.metrics import precision_recall_curve

def precision_recall_curve_plot(y_test , prediction_proba_class1):

    precisions, recalls, thresholds = precision_recall_curve(y_test, prediction_proba_class1)
    
    # X축: threshold
    # Y축: 정밀도, 재현율 
    # 정밀도는 점선으로 표시
    plt.figure(figsize=(8,6))
    threshold_boundary = thresholds.shape[0]
    plt.plot(thresholds, precisions[0:threshold_boundary], linestyle='--', label='precision')
    plt.plot(thresholds, recalls[0:threshold_boundary],label='recall')
    
    # X축(threshold)의 Scale을 0 ~ 1 단위로 변경
    start, end = plt.xlim()
    plt.xticks(np.round(np.arange(start, end, 0.1),2))
    
    plt.xlabel('Threshold value'); plt.ylabel('Precision and Recall value')
    plt.legend()
    plt.grid()
    plt.show()
    
precision_recall_curve_plot(y_test, lg.predict_proba(X_test)[:, 1] )

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

sns.scatterplot(x="pca1", y="pca2", hue='target', data=pca_train_df, alpha=0.5)
plt.show()

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

features, targets = pre_s_df.iloc[:, :-1], pre_s_df.iloc[:, -1]

X_train, X_test, y_train, y_test = \
train_test_split(features, targets, test_size=0.2, random_state=321)

l_r = LinearRegression()
l_r.fit(X_train, y_train)

In [ ]:
import numpy as np
from sklearn.metrics import mean_squared_log_error, mean_squared_error, r2_score

def get_evaluation(y_test, prediction):
    MSE = mean_squared_error(y_test, prediction)
    RMSE = np.sqrt(MSE)
    MSLE = mean_squared_log_error(y_test, prediction)
    RMSLE = np.sqrt(mean_squared_log_error(y_test, prediction))
    R2 = r2_score(y_test, prediction)
    print('MSE: {:.4f}, RMSE: {:.4f}, MSLE: {:.4f}, RMSLE: {:.4f}, R2: {:.4f}'\
          .format(MSE, RMSE, MSLE, RMSLE, R2))

In [ ]:
import numpy as np
from sklearn.metrics import mean_squared_log_error, mean_squared_error, r2_score

def get_evaluation_negative(y_test, prediction):
    MSE = mean_squared_error(y_test, prediction)
    RMSE = np.sqrt(MSE)
    # MSLE = mean_squared_log_error(y_test, prediction)
    # RMSLE = np.sqrt(mean_squared_log_error(y_test, prediction))
    R2 = r2_score(y_test, prediction)
    # print('MSE: {:.4f}, RMSE: {:.4f}, MSLE: {:.4f}, RMSLE: {:.4f}, R2: {:.4f}'\
    #       .format(MSE, RMSE, MSLE, RMSLE, R2))
    print('MSE: {:.4f}, RMSE: {:.4f}, R2: {:.4f}'\
          .format(MSE, RMSE, R2))

In [ ]:
prediction = l_r.predict(X_test)
get_evaluation_negative(y_test, prediction)

# 차원축소

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA


for i in range(12):
    pca = PCA(n_components=(i+1))

    pca_train = pca.fit_transform(features)

    print(pca.explained_variance_ratio_.sum(), i)

In [ ]:
# 보존률
print(pca.explained_variance_ratio_)
print(pca.explained_variance_ratio_.sum())

In [ ]:
# 파이프라인 구축 후 차원 축소 후 선형 회귀 분석
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline

features, targets = pre_s_df.iloc[:,:-1], pre_s_df.iloc[:,-1]

X_train, X_test, y_train, y_test = \
train_test_split(features,targets, test_size=0.2, random_state=321)

pipe = Pipeline(
    [
        ('pca', PCA(n_components=3)),
        ('l_r',LinearRegression())
    ]
)

pipe.fit(X_train, y_train)

In [ ]:
prediction = pipe.predict(X_test)
get_evaluation_negative(y_test, prediction)

In [ ]:
# from sklearn.model_selection import train_test_split
# from sklearn.preprocessing import PolynomialFeatures
# from sklearn.linear_model import LinearRegression

# poly_features = PolynomialFeatures(degree=2).fit_transform(features)

# X_train, X_test, y_train, y_test =\
# train_test_split(poly_features, targets, test_size=0.2, random_state=321)

# l_r = LinearRegression()
# l_r.fit(X_train, y_train)

In [ ]:
# prediction = l_r.predict(X_test)
# get_evaluation_negative(y_test, prediction)

# Cycle02
- 데이터 전처리 진행
-